/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitesIndexRouteImport } from './routes/invites/index'
import { Route as InvitesInviteIdRouteImport } from './routes/invites/$inviteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesIndexRoute = InvitesIndexRouteImport.update({
  id: '/invites/',
  path: '/invites/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesInviteIdRoute = InvitesInviteIdRouteImport.update({
  id: '/invites/$inviteId',
  path: '/invites/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invites/$inviteId': typeof InvitesInviteIdRoute
  '/invites': typeof InvitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invites/$inviteId': typeof InvitesInviteIdRoute
  '/invites': typeof InvitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invites/$inviteId': typeof InvitesInviteIdRoute
  '/invites/': typeof InvitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invites/$inviteId' | '/invites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invites/$inviteId' | '/invites'
  id: '__root__' | '/' | '/invites/$inviteId' | '/invites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitesInviteIdRoute: typeof InvitesInviteIdRoute
  InvitesIndexRoute: typeof InvitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/': {
      id: '/invites/'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$inviteId': {
      id: '/invites/$inviteId'
      path: '/invites/$inviteId'
      fullPath: '/invites/$inviteId'
      preLoaderRoute: typeof InvitesInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitesInviteIdRoute: InvitesInviteIdRoute,
  InvitesIndexRoute: InvitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
