/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Connect
 * Full-stack app.
 * OpenAPI spec version: 1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useQuery } from '@tanstack/react-query'

import type {
  GetInvitesSubscriberId302,
  GetInvitesSubscriberId404,
  GetRanking200,
  GetRanking404,
  GetSubscribersSubscriberIdRanking200,
  GetSubscribersSubscriberIdRanking404,
  GetSubscribersSubscriberIdRankingClicks200,
  GetSubscribersSubscriberIdRankingClicks404,
  GetSubscribersSubscriberIdRankingCount200,
  GetSubscribersSubscriberIdRankingCount404,
} from '../../models'
import { customFetch } from '.././custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Access invite link and redirects user
 */
export const getGetInvitesSubscriberIdUrl = (subscriberId: string) => {
  return `http://localhost:3333/invites/${subscriberId}`
}

export const getInvitesSubscriberId = async (
  subscriberId: string,
  options?: RequestInit,
): Promise<unknown> => {
  return customFetch<unknown>(getGetInvitesSubscriberIdUrl(subscriberId), {
    ...options,
    method: 'GET',
  })
}

export const getGetInvitesSubscriberIdQueryKey = (subscriberId?: string) => {
  return [`http://localhost:3333/invites/${subscriberId}`] as const
}

export const getGetInvitesSubscriberIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getInvitesSubscriberId>>,
  TError = GetInvitesSubscriberId302 | GetInvitesSubscriberId404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInvitesSubscriberId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetInvitesSubscriberIdQueryKey(subscriberId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getInvitesSubscriberId>>
  > = ({ signal }) =>
    getInvitesSubscriberId(subscriberId, {
      signal,
      ...requestOptions,
    })

  return {
    queryKey,
    queryFn,
    enabled: !!subscriberId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getInvitesSubscriberId>>,
    TError,
    TData
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetInvitesSubscriberIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInvitesSubscriberId>>
>
export type GetInvitesSubscriberIdQueryError =
  | GetInvitesSubscriberId302
  | GetInvitesSubscriberId404

export function useGetInvitesSubscriberId<
  TData = Awaited<ReturnType<typeof getInvitesSubscriberId>>,
  TError = GetInvitesSubscriberId302 | GetInvitesSubscriberId404,
>(
  subscriberId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInvitesSubscriberId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvitesSubscriberId>>,
          TError,
          Awaited<ReturnType<typeof getInvitesSubscriberId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInvitesSubscriberId<
  TData = Awaited<ReturnType<typeof getInvitesSubscriberId>>,
  TError = GetInvitesSubscriberId302 | GetInvitesSubscriberId404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInvitesSubscriberId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvitesSubscriberId>>,
          TError,
          Awaited<ReturnType<typeof getInvitesSubscriberId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInvitesSubscriberId<
  TData = Awaited<ReturnType<typeof getInvitesSubscriberId>>,
  TError = GetInvitesSubscriberId302 | GetInvitesSubscriberId404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInvitesSubscriberId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Access invite link and redirects user
 */

export function useGetInvitesSubscriberId<
  TData = Awaited<ReturnType<typeof getInvitesSubscriberId>>,
  TError = GetInvitesSubscriberId302 | GetInvitesSubscriberId404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInvitesSubscriberId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetInvitesSubscriberIdQueryOptions(
    subscriberId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get subscriber invite clicks count
 */
export const getGetSubscribersSubscriberIdRankingClicksUrl = (
  subscriberId: string,
) => {
  return `http://localhost:3333/subscribers/${subscriberId}/ranking/clicks`
}

export const getSubscribersSubscriberIdRankingClicks = async (
  subscriberId: string,
  options?: RequestInit,
): Promise<GetSubscribersSubscriberIdRankingClicks200> => {
  return customFetch<GetSubscribersSubscriberIdRankingClicks200>(
    getGetSubscribersSubscriberIdRankingClicksUrl(subscriberId),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getGetSubscribersSubscriberIdRankingClicksQueryKey = (
  subscriberId?: string,
) => {
  return [
    `http://localhost:3333/subscribers/${subscriberId}/ranking/clicks`,
  ] as const
}

export const getGetSubscribersSubscriberIdRankingClicksQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
  TError = GetSubscribersSubscriberIdRankingClicks404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetSubscribersSubscriberIdRankingClicksQueryKey(subscriberId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>
  > = ({ signal }) =>
    getSubscribersSubscriberIdRankingClicks(subscriberId, {
      signal,
      ...requestOptions,
    })

  return {
    queryKey,
    queryFn,
    enabled: !!subscriberId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
    TError,
    TData
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetSubscribersSubscriberIdRankingClicksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>
>
export type GetSubscribersSubscriberIdRankingClicksQueryError =
  GetSubscribersSubscriberIdRankingClicks404

export function useGetSubscribersSubscriberIdRankingClicks<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
  TError = GetSubscribersSubscriberIdRankingClicks404,
>(
  subscriberId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
          TError,
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSubscribersSubscriberIdRankingClicks<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
  TError = GetSubscribersSubscriberIdRankingClicks404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
          TError,
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSubscribersSubscriberIdRankingClicks<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
  TError = GetSubscribersSubscriberIdRankingClicks404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get subscriber invite clicks count
 */

export function useGetSubscribersSubscriberIdRankingClicks<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
  TError = GetSubscribersSubscriberIdRankingClicks404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingClicks>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetSubscribersSubscriberIdRankingClicksQueryOptions(
    subscriberId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get subscriber invites count
 */
export const getGetSubscribersSubscriberIdRankingCountUrl = (
  subscriberId: string,
) => {
  return `http://localhost:3333/subscribers/${subscriberId}/ranking/count`
}

export const getSubscribersSubscriberIdRankingCount = async (
  subscriberId: string,
  options?: RequestInit,
): Promise<GetSubscribersSubscriberIdRankingCount200> => {
  return customFetch<GetSubscribersSubscriberIdRankingCount200>(
    getGetSubscribersSubscriberIdRankingCountUrl(subscriberId),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getGetSubscribersSubscriberIdRankingCountQueryKey = (
  subscriberId?: string,
) => {
  return [
    `http://localhost:3333/subscribers/${subscriberId}/ranking/count`,
  ] as const
}

export const getGetSubscribersSubscriberIdRankingCountQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
  TError = GetSubscribersSubscriberIdRankingCount404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetSubscribersSubscriberIdRankingCountQueryKey(subscriberId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>
  > = ({ signal }) =>
    getSubscribersSubscriberIdRankingCount(subscriberId, {
      signal,
      ...requestOptions,
    })

  return {
    queryKey,
    queryFn,
    enabled: !!subscriberId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
    TError,
    TData
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetSubscribersSubscriberIdRankingCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>
>
export type GetSubscribersSubscriberIdRankingCountQueryError =
  GetSubscribersSubscriberIdRankingCount404

export function useGetSubscribersSubscriberIdRankingCount<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
  TError = GetSubscribersSubscriberIdRankingCount404,
>(
  subscriberId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
          TError,
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSubscribersSubscriberIdRankingCount<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
  TError = GetSubscribersSubscriberIdRankingCount404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
          TError,
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSubscribersSubscriberIdRankingCount<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
  TError = GetSubscribersSubscriberIdRankingCount404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get subscriber invites count
 */

export function useGetSubscribersSubscriberIdRankingCount<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
  TError = GetSubscribersSubscriberIdRankingCount404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRankingCount>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetSubscribersSubscriberIdRankingCountQueryOptions(
    subscriberId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get subscriber ranking position
 */
export const getGetSubscribersSubscriberIdRankingUrl = (
  subscriberId: string,
) => {
  return `http://localhost:3333/subscribers/${subscriberId}/ranking`
}

export const getSubscribersSubscriberIdRanking = async (
  subscriberId: string,
  options?: RequestInit,
): Promise<GetSubscribersSubscriberIdRanking200> => {
  return customFetch<GetSubscribersSubscriberIdRanking200>(
    getGetSubscribersSubscriberIdRankingUrl(subscriberId),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getGetSubscribersSubscriberIdRankingQueryKey = (
  subscriberId?: string,
) => {
  return [`http://localhost:3333/subscribers/${subscriberId}/ranking`] as const
}

export const getGetSubscribersSubscriberIdRankingQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
  TError = GetSubscribersSubscriberIdRanking404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetSubscribersSubscriberIdRankingQueryKey(subscriberId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>
  > = ({ signal }) =>
    getSubscribersSubscriberIdRanking(subscriberId, {
      signal,
      ...requestOptions,
    })

  return {
    queryKey,
    queryFn,
    enabled: !!subscriberId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
    TError,
    TData
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetSubscribersSubscriberIdRankingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>
>
export type GetSubscribersSubscriberIdRankingQueryError =
  GetSubscribersSubscriberIdRanking404

export function useGetSubscribersSubscriberIdRanking<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
  TError = GetSubscribersSubscriberIdRanking404,
>(
  subscriberId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
          TError,
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSubscribersSubscriberIdRanking<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
  TError = GetSubscribersSubscriberIdRanking404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
          TError,
          Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSubscribersSubscriberIdRanking<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
  TError = GetSubscribersSubscriberIdRanking404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get subscriber ranking position
 */

export function useGetSubscribersSubscriberIdRanking<
  TData = Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
  TError = GetSubscribersSubscriberIdRanking404,
>(
  subscriberId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubscribersSubscriberIdRanking>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetSubscribersSubscriberIdRankingQueryOptions(
    subscriberId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get ranking
 */
export const getGetRankingUrl = () => {
  return `http://localhost:3333/ranking`
}

export const getRanking = async (
  options?: RequestInit,
): Promise<GetRanking200> => {
  return customFetch<GetRanking200>(getGetRankingUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetRankingQueryKey = () => {
  return [`http://localhost:3333/ranking`] as const
}

export const getGetRankingQueryOptions = <
  TData = Awaited<ReturnType<typeof getRanking>>,
  TError = GetRanking404,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getRanking>>, TError, TData>
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetRankingQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRanking>>> = ({
    signal,
  }) =>
    getRanking({
      signal,
      ...requestOptions,
    })

  return {
    queryKey,
    queryFn,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getRanking>>,
    TError,
    TData
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetRankingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRanking>>
>
export type GetRankingQueryError = GetRanking404

export function useGetRanking<
  TData = Awaited<ReturnType<typeof getRanking>>,
  TError = GetRanking404,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRanking>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRanking>>,
          TError,
          Awaited<ReturnType<typeof getRanking>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetRanking<
  TData = Awaited<ReturnType<typeof getRanking>>,
  TError = GetRanking404,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRanking>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRanking>>,
          TError,
          Awaited<ReturnType<typeof getRanking>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetRanking<
  TData = Awaited<ReturnType<typeof getRanking>>,
  TError = GetRanking404,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRanking>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get ranking
 */

export function useGetRanking<
  TData = Awaited<ReturnType<typeof getRanking>>,
  TError = GetRanking404,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRanking>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetRankingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
