/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Connect
 * Full-stack app.
 * OpenAPI spec version: 1.0.0
 */
import type { GetRanking200RankingItem } from './get-ranking200-ranking-item'

export type GetRanking200 = {
  ranking: GetRanking200RankingItem[]
}
