/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Connect
 * Full-stack app.
 * OpenAPI spec version: 1.0.0
 */

export type GetSubscribersSubscriberIdRankingClicks200 = {
  count?: number
}
