/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Connect
 * Full-stack app.
 * OpenAPI spec version: 1.0.0
 */

export type GetRanking200RankingItem = {
  id: string
  name: string
  email: string
  createdAt: string
  score?: number
}
