/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Connect
 * Full-stack app.
 * OpenAPI spec version: 1.0.0
 */
import type { PostSubscriptions400Issue } from './post-subscriptions400-issue'

export type PostSubscriptions400 = {
  message: string
  issue: PostSubscriptions400Issue
}
