@baseUrl = http://localhost:3333
@subscriberId = {{ create_subscription.response.body.subscriberId }}

# @name create_subscription
POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "name": "John doe",
  "email": "john.doe@example.com"  
}

###

# @name create_subscription_with_referrer
POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "name": "Lucas Doe",
  "email": "lucas.doe@example.com",
  "referrer": "{{subscriberId}}" 
}

###
# @name access_invite_link
GET {{baseUrl}}/invites/{{subscriberId}}

###
# @name get_subscriber_invite_clicks
GET {{baseUrl}}/subscribers/{{subscriberId}}/ranking/clicks

###
# @name get_subscriber_invites_count
GET {{baseUrl}}/subscribers/{{subscriberId}}/ranking/count

###
# @name get_subscriber_ranking_position
GET {{baseUrl}}/subscribers/{{subscriberId}}/ranking

###
# @name get_ranking
GET {{baseUrl}}/ranking