@baseUrl = http://localhost:3333
@subscriberId = {{ create_subscription.response.body.subscriberId }}

# @name create_subscription
POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"  
}

###

# @name create_subscription_with_referrer
POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "name": "Jana Doe",
  "email": "jana.doe@example.com",
  "referrer": "{{subscriberId}}" 
}

###
# @name access_invite_link
GET {{baseUrl}}/invites/{{subscriberId}}

###
# @name get_subscriber_invite_clicks
GET {{baseUrl}}/subscribers/{{subscriberId}}/ranking/clicks

###
# @name get_subscriber_invites_count
GET {{baseUrl}}/subscribers/{{subscriberId}}/ranking/count